version: "3"
services:
  mainnetwork:
    ports:
      - "7888:7888"
      - "3000:3000"
      - "8889:8888"
      - "4010:4010"
  flow-services:
    image: clojure:openjdk-8-lein-2.9.1
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
      - ~/.lein:/root/.lein
    working_dir: /app
    command: ./dev/start-dev-env.sh
  wiremock-proxy:
    ports:
      - 8081:8080
#   volumes:
#     - ./record:/home/wiremock
#   command: --proxy-all="http://192.168.0.100:8888" --record-mappings --verbose
