version: "3"
services:
  mainnetwork:
    image: alpine
    command: tail -f /dev/null
  gae-dev-server:
    build: gae-dev-server
    network_mode: service:mainnetwork
    volumes:
      - ~/.m2:/opt/m2/
  flow-services:
    network_mode: service:mainnetwork
    environment:
      - HOST_UID
      - HOST_GID
      - EMAIL_PASSWORD=anything
      - EMAIL_USER=anything.else
      - APP_VERSION=some.version
  wiremock-proxy:
    image: rodolpheche/wiremock:2.16.0-alpine
  aws-s3:
    image: abhin4v/hastatic:1.0.0
    environment:
      - PORT=3005
    command: /usr/bin/hastatic
    working_dir: /s3
    volumes:
      - ./s3:/s3:ro
