version: "3"
services:
 mainnetwork:
    image: alpine
    command: tail -f /dev/null
 gae-dev-server:
   build: gae-dev-server
   network_mode: service:mainnetwork
 backend:
   network_mode: service:mainnetwork
   environment:
     - HOST_UID
     - HOST_GID
     - EMAIL_PASSWORD=anything
     - EMAIL_USER=anything.else
 wiremock-proxy:
   image: rodolpheche/wiremock:2.16.0-alpine
   ports:
     - 8081:8080
   volumes:
     - ./record:/home/wiremock
#   command: --proxy-all="http://192.168.0.100:8888" --record-mappings --verbose