version: "3"
services:

  backend:
    volumes:
      - ./backend/dev:/app/dev
      - ./backend/dev:/etc/config/akvo-flow-services
    image: "eu.gcr.io/${PROJECT_NAME}/akvo-flow-services:$TRAVIS_COMMIT"

  tests:
    image: akvo-flow-services-dev:develop
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
      - ~/.lein:/root/.lein
    depends_on:
      - backend
    command: "true"
