version: "3"
services:
 mainnetwork:
    ports:
      - "7888:7888"
      - "3000:3000"
      - "8888:8888"
 backend:
   build:
     context: .
     dockerfile: dev/Dockerfile-dev
   volumes:
      - .:/app
      - ~/.m2:/root/.m2
      - ~/.lein:/root/.lein