version: "3"
services:
 backend:
   build:
     context: .
     dockerfile: backend/Dockerfile-dev
   network_mode: host
   environment:
     - HOST_UID
     - HOST_GID
     - EMAIL_PASSWORD=anything
     - EMAIL_USER=anything.else
     - WIREMOCK_URL=localhost:8080
   volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
      - ~/.lein:/root/.lein

 wiremock-proxy:
   image: rodolpheche/wiremock:2.16.0-alpine
   network_mode: host
   volumes:
     - ./wiremock:/etc/wiremock/files
   command: --root-dir /etc/wiremock/files --no-request-journal --verbose