FROM clojure:lein-2.7.1
MAINTAINER Akvo Foundation <devops@akvo.org>

COPY dev/start-dev-env.sh /app/start-dev-env.sh

RUN chmod u+x /app/start-dev-env.sh

WORKDIR /app

CMD [ "dev/start-dev-env.sh" ]
